### ISSUE TITLE
Offline-aadhaar-e-kyc-verification-example

### ISSUE THREAD

**Issue by kombiahrk** [GovindaPaliwal/Offline-aadhaar-e-kyc-verification-example#2]
Hai i need the code in php. 
atleast i need the XML Verification Part in PHP Code...

**Comment by GovindaPaliwal** [comment]
solved your problem ?  Will try to create same in php and upload seperately.

**Comment by kombiahrk** [comment]
Not Yet...
If you do that i very thankful to you.

**Comment by kombiahrk** [comment]
Problem Solved Some what i managed to do this in PHP
https://github.com/kombiahrk/Offline-Aadhaar-EKYC-Verification
